#pragma once

// â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
// Suraksha Version & Build Number Definition
// Automatically generated by scripts/Set-Version.ps1
// â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

#define SURAKSHA_VERSION_MAJOR      2
#define SURAKSHA_VERSION_MINOR      0
#define SURAKSHA_VERSION_PATCH      1
#define SURAKSHA_VERSION_BUILD      0

#define SURAKSHA_VERSION_STRING     L"2.0.1"
#define SURAKSHA_BUILD_TAG          L"0004.15082026-S-v2.0.1"
#define SURAKSHA_IS_BETA            false

#if SURAKSHA_IS_BETA
    #define SURAKSHA_DISPLAY_VERSION L"2.0.1-beta [Build 0004.15082026-S-v2.0.1]"
#else
    #define SURAKSHA_DISPLAY_VERSION L"2.0.1 [Build 0004.15082026-S-v2.0.1]"
#endif
