#pragma once

// ============================================================================
// Suraksha Version & Apple-Style Build Definition
// Automatically generated by scripts/Set-Version.ps1
// ============================================================================ 

#define SURAKSHA_VERSION_MAJOR      2
#define SURAKSHA_VERSION_MINOR      0
#define SURAKSHA_VERSION_PATCH      0
#define SURAKSHA_VERSION_BUILD      0

#define SURAKSHA_VERSION_STRING     L"2.0.0"
#define SURAKSHA_BUILD_TAG          L"26S0815c"
#define SURAKSHA_IS_BETA            false

#if SURAKSHA_IS_BETA
    #define SURAKSHA_DISPLAY_VERSION L"2.0.0-beta (26S0815c)"
#else
    #define SURAKSHA_DISPLAY_VERSION L"2.0.0 (26S0815c)"
#endif
