#pragma once

// ═══════════════════════════════════════════════════════════════
// Suraksha Version & Apple-Style Build Definition
// Automatically generated by scripts/Set-Version.ps1
// ═══════════════════════════════════════════════════════════════

#define SURAKSHA_VERSION_MAJOR      2
#define SURAKSHA_VERSION_MINOR      0
#define SURAKSHA_VERSION_PATCH      1
#define SURAKSHA_VERSION_BUILD      0

#define SURAKSHA_VERSION_STRING     L"2.0.1"
#define SURAKSHA_BUILD_TAG          L"26B0815a"
#define SURAKSHA_IS_BETA            true

#if SURAKSHA_IS_BETA
    #define SURAKSHA_DISPLAY_VERSION L"2.0.1-beta (26B0815a)"
#else
    #define SURAKSHA_DISPLAY_VERSION L"2.0.1 (26B0815a)"
#endif
