<#
.SYNOPSIS
    Suraksha Apple-Style Automated Build & Version Manager
.DESCRIPTION
    Generates Apple-inspired compact build codes (e.g. 26B0815a, 26B0815b)
    Format: [YY][Channel B/S][MMDD][Iteration a, b, c...]
    Supports -beta and -release switches with automatic daily iteration detection.
.EXAMPLE
    .\scripts\Set-Version.ps1 -beta
.EXAMPLE
    .\scripts\Set-Version.ps1 -release
#>

param (
    [switch]$beta,
    [switch]$release,
    [string]$Version = ""
)

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  Suraksha Build & Version Manager (Apple HIG)" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan

# Determine channel
$isBeta = $true
if ($release) {
    $isBeta = $false
} elseif ($beta) {
    $isBeta = $true
}

# 1. Read current version from Version.h
$versionHPath = "Version.h"
if (-not (Test-Path $versionHPath)) {
    Write-Error "Version.h not found in project root!"
    exit 1
}

$versionHContent = Get-Content $versionHPath -Raw

$major = 2
$minor = 0
$patch = 0
$wasBeta = $false
$prevBuildTag = ""

if ($versionHContent -match '#define\s+SURAKSHA_VERSION_MAJOR\s+(\d+)') { $major = [int]$Matches[1] }
if ($versionHContent -match '#define\s+SURAKSHA_VERSION_MINOR\s+(\d+)') { $minor = [int]$Matches[1] }
if ($versionHContent -match '#define\s+SURAKSHA_VERSION_PATCH\s+(\d+)') { $patch = [int]$Matches[1] }
if ($versionHContent -match '#define\s+SURAKSHA_IS_BETA\s+(true|false)') { $wasBeta = ($Matches[1] -eq "true") }
if ($versionHContent -match '#define\s+SURAKSHA_BUILD_TAG\s+L"([^"]+)"') { $prevBuildTag = $Matches[1] }

Write-Host "Previous State: v$major.$minor.$patch (Beta: $wasBeta, Last Build: $prevBuildTag)" -ForegroundColor DarkGray

# 2. Determine Semantic Version
if ($Version) {
    if ($Version -match '^(\d+)\.(\d+)\.(\d+)') {
        $newMajor = [int]$Matches[1]
        $newMinor = [int]$Matches[2]
        $newPatch = [int]$Matches[3]
    } else {
        Write-Error "Invalid version format '$Version'. Expected format: 2.1.0"
        exit 1
    }
} else {
    $newMajor = $major
    $newMinor = $minor
    $newPatch = $patch

    if ($isBeta) {
        # Advance patch when moving from stable to beta
        if (-not $wasBeta) {
            $newPatch++
        }
    } else {
        # If moving from beta to stable, keep patch (or bump minor if already stable)
        if (-not $wasBeta) {
            $newMinor++
            $newPatch = 0
        }
    }
}

$semVer = "$newMajor.$newMinor.$newPatch"
$channelChar = if ($isBeta) { "B" } else { "S" }
$channelName = if ($isBeta) { "Beta" } else { "Stable" }

# 3. Generate Apple-Style Compact Build Code: [YY][Channel][MMDD][Suffix a, b, c...]
$todayYY = Get-Date -Format "yy"
$todayMMDD = Get-Date -Format "MMdd"
$todayBaseTag = "$todayYY$channelChar$todayMMDD"

$suffix = "a"
if ($isBeta) {
    # Check if we already built a beta today
    if ($prevBuildTag -match "^$todayBaseTag([a-z]?)$") {
        $currentSuffix = $Matches[1]
        if ([string]::IsNullOrEmpty($currentSuffix)) {
            $suffix = "b"
        } else {
            # Increment letter: a -> b, b -> c, etc.
            $charVal = [int][char]$currentSuffix
            $nextChar = [char]($charVal + 1)
            $suffix = [string]$nextChar
        }
    } else {
        $suffix = "a"
    }
    $buildTag = "$todayBaseTag$suffix"
} else {
    # For Stable: first release of day has no letter, subsequent get b, c...
    if ($prevBuildTag -match "^$todayBaseTag([a-z]?)$") {
        $currentSuffix = $Matches[1]
        if ([string]::IsNullOrEmpty($currentSuffix)) {
            $suffix = "b"
        } else {
            $charVal = [int][char]$currentSuffix
            $nextChar = [char]($charVal + 1)
            $suffix = [string]$nextChar
        }
        $buildTag = "$todayBaseTag$suffix"
    } else {
        $buildTag = "$todayBaseTag"
    }
}

$rawDisplayVer = if ($isBeta) { "$semVer-beta" } else { "$semVer" }
$displayVersion = if ($isBeta) { "$semVer-beta ($buildTag)" } else { "$semVer ($buildTag)" }
$msixVersion = "$newMajor.$newMinor.$newPatch.0"

Write-Host ""
Write-Host "Generated New Apple-Style Build Profile:" -ForegroundColor Yellow
Write-Host "  * Channel:         $channelName ($channelChar)" -ForegroundColor White
Write-Host "  * Semantic Ver:    $semVer" -ForegroundColor White
Write-Host "  * Apple Build Tag: $buildTag" -ForegroundColor Cyan
Write-Host "  * Display String:  $displayVersion" -ForegroundColor White
Write-Host "  * MSIX Version:    $msixVersion" -ForegroundColor White
Write-Host ""

# 4. Update Version.h
$isBetaLiteral = if ($isBeta) { "true" } else { "false" }
$lines = @(
    "#pragma once",
    "",
    "// ═══════════════════════════════════════════════════════════════",
    "// Suraksha Version & Apple-Style Build Definition",
    "// Automatically generated by scripts/Set-Version.ps1",
    "// ═══════════════════════════════════════════════════════════════",
    "",
    "#define SURAKSHA_VERSION_MAJOR      $newMajor",
    "#define SURAKSHA_VERSION_MINOR      $newMinor",
    "#define SURAKSHA_VERSION_PATCH      $newPatch",
    "#define SURAKSHA_VERSION_BUILD      0",
    "",
    "#define SURAKSHA_VERSION_STRING     L`"$semVer`"",
    "#define SURAKSHA_BUILD_TAG          L`"$buildTag`"",
    "#define SURAKSHA_IS_BETA            $isBetaLiteral",
    "",
    "#if SURAKSHA_IS_BETA",
    "    #define SURAKSHA_DISPLAY_VERSION L`"$semVer-beta ($buildTag)`"",
    "#else",
    "    #define SURAKSHA_DISPLAY_VERSION L`"$semVer ($buildTag)`"",
    "#endif"
)
$lines | Out-File -FilePath "Version.h" -Encoding utf8
Write-Host "[OK] Updated Version.h" -ForegroundColor Green

# 5. Update SurakshaSetup.iss
if (Test-Path "SurakshaSetup.iss") {
    $issContent = Get-Content "SurakshaSetup.iss" -Raw
    $issContent = $issContent -replace '#define MyAppVersion "[^"]+"', "#define MyAppVersion `"$rawDisplayVer`""
    $issContent | Out-File -FilePath "SurakshaSetup.iss" -Encoding utf8
    Write-Host "[OK] Updated SurakshaSetup.iss" -ForegroundColor Green
}

# 6. Update packaging/AppxManifest.xml
if (Test-Path "packaging\AppxManifest.xml") {
    [xml]$manifest = Get-Content "packaging\AppxManifest.xml"
    $manifest.Package.Identity.Version = $msixVersion
    $manifest.Save((Resolve-Path "packaging\AppxManifest.xml"))
    Write-Host "[OK] Updated packaging/AppxManifest.xml" -ForegroundColor Green
}

# 7. Update README.md
if (Test-Path "README.md") {
    $readme = Get-Content "README.md" -Raw
    $readme = [regex]::Replace($readme, '# Suraksha.*?\n', "# Suraksha - Privacy & Security (v$rawDisplayVer)`n")
    $readme | Out-File -FilePath "README.md" -Encoding utf8
    Write-Host "[OK] Updated README.md" -ForegroundColor Green
}

Write-Host ""
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  Apple Build Code: $buildTag ($displayVersion)" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Cyan
