<#
.SYNOPSIS
    Suraksha Automated Version & Build Tag Manager
.DESCRIPTION
    Automatically detects current version, increments version based on -beta or -release,
    generates a timestamped build number (Time + Date + Channel [B/S] + Version),
    and updates all project files.
.EXAMPLE
    .\scripts\Set-Version.ps1 -beta
.EXAMPLE
    .\scripts\Set-Version.ps1 -release
#>

param (
    [switch]$beta,
    [switch]$release,
    [string]$Version = ""
)

Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  Suraksha Build & Version Manager" -ForegroundColor Cyan
Write-Host "=========================================" -ForegroundColor Cyan

# Determine mode (default to beta if neither specified, or pick the switch provided)
$isBeta = $true
if ($release) {
    $isBeta = $false
} elseif ($beta) {
    $isBeta = $true
}

# 1. Read current version and status from Version.h
$versionHPath = "Version.h"
if (-not (Test-Path $versionHPath)) {
    Write-Error "Version.h not found in project root!"
    exit 1
}

$versionHContent = Get-Content $versionHPath -Raw

$major = 2
$minor = 0
$patch = 0
$wasBeta = $false

if ($versionHContent -match '#define\s+SURAKSHA_VERSION_MAJOR\s+(\d+)') { $major = [int]$Matches[1] }
if ($versionHContent -match '#define\s+SURAKSHA_VERSION_MINOR\s+(\d+)') { $minor = [int]$Matches[1] }
if ($versionHContent -match '#define\s+SURAKSHA_VERSION_PATCH\s+(\d+)') { $patch = [int]$Matches[1] }
if ($versionHContent -match '#define\s+SURAKSHA_IS_BETA\s+(true|false)') { $wasBeta = ($Matches[1] -eq "true") }

Write-Host "Previous State: v$major.$minor.$patch (Beta: $wasBeta)" -ForegroundColor DarkGray

# 2. Compute Next Version
if ($Version) {
    if ($Version -match '^(\d+)\.(\d+)\.(\d+)') {
        $newMajor = [int]$Matches[1]
        $newMinor = [int]$Matches[2]
        $newPatch = [int]$Matches[3]
    } else {
        Write-Error "Invalid version format '$Version'. Expected format: 2.1.0"
        exit 1
    }
} else {
    $newMajor = $major
    $newMinor = $minor
    $newPatch = $patch

    if ($isBeta) {
        # If transitioning to beta or advancing beta, bump patch (X.X.1 or X.1.X)
        $newPatch++
    } else {
        # If releasing stable: graduate beta (or bump minor if already stable)
        if ($wasBeta) {
            # Graduate beta to stable version
            $newPatch = $patch
        } else {
            # Next stable minor release
            $newMinor++
            $newPatch = 0
        }
    }
}

$semVer = "$newMajor.$newMinor.$newPatch"
$channelChar = if ($isBeta) { "B" } else { "S" }
$channelName = if ($isBeta) { "Beta" } else { "Stable" }

# Timestamp format: Time(HHmm) + Date(ddMMyyyy)
$timeDate = Get-Date -Format "HHmm.ddMMyyyy"
# Build Number: Time.Date.Channel.Version (e.g. 0005.15082026.B.v2.0.1 or 0005.15082026.S.v2.1.0)
$buildTag = "$timeDate-$channelChar-v$semVer"

$rawDisplayVer = if ($isBeta) { "$semVer-beta" } else { "$semVer" }
$displayVersion = if ($isBeta) { "$semVer-beta (Build: $buildTag)" } else { "$semVer (Build: $buildTag)" }
$msixVersion = "$newMajor.$newMinor.$newPatch.0"

Write-Host ""
Write-Host "Generated New Build Profile:" -ForegroundColor Yellow
Write-Host "  * Channel:         $channelName ($channelChar)" -ForegroundColor White
Write-Host "  * Semantic Ver:    $semVer" -ForegroundColor White
Write-Host "  * Build Number:    $buildTag" -ForegroundColor White
Write-Host "  * Display Version: $displayVersion" -ForegroundColor White
Write-Host "  * MSIX Version:    $msixVersion" -ForegroundColor White
Write-Host ""

# 3. Update Version.h
$isBetaLiteral = if ($isBeta) { "true" } else { "false" }
$lines = @(
    "#pragma once",
    "",
    "// ═══════════════════════════════════════════════════════════════",
    "// Suraksha Version & Build Number Definition",
    "// Automatically generated by scripts/Set-Version.ps1",
    "// ═══════════════════════════════════════════════════════════════",
    "",
    "#define SURAKSHA_VERSION_MAJOR      $newMajor",
    "#define SURAKSHA_VERSION_MINOR      $newMinor",
    "#define SURAKSHA_VERSION_PATCH      $newPatch",
    "#define SURAKSHA_VERSION_BUILD      0",
    "",
    "#define SURAKSHA_VERSION_STRING     L`"$semVer`"",
    "#define SURAKSHA_BUILD_TAG          L`"$buildTag`"",
    "#define SURAKSHA_IS_BETA            $isBetaLiteral",
    "",
    "#if SURAKSHA_IS_BETA",
    "    #define SURAKSHA_DISPLAY_VERSION L`"$semVer-beta [Build $buildTag]`"",
    "#else",
    "    #define SURAKSHA_DISPLAY_VERSION L`"$semVer [Build $buildTag]`"",
    "#endif"
)
$lines | Out-File -FilePath "Version.h" -Encoding utf8
Write-Host "[OK] Updated Version.h" -ForegroundColor Green

# 4. Update SurakshaSetup.iss
if (Test-Path "SurakshaSetup.iss") {
    $issContent = Get-Content "SurakshaSetup.iss" -Raw
    $issContent = $issContent -replace '#define MyAppVersion "[^"]+"', "#define MyAppVersion `"$rawDisplayVer`""
    $issContent | Out-File -FilePath "SurakshaSetup.iss" -Encoding utf8
    Write-Host "[OK] Updated SurakshaSetup.iss" -ForegroundColor Green
}

# 5. Update packaging/AppxManifest.xml
if (Test-Path "packaging\AppxManifest.xml") {
    [xml]$manifest = Get-Content "packaging\AppxManifest.xml"
    $manifest.Package.Identity.Version = $msixVersion
    $manifest.Save((Resolve-Path "packaging\AppxManifest.xml"))
    Write-Host "[OK] Updated packaging/AppxManifest.xml" -ForegroundColor Green
}

# 6. Update README.md
if (Test-Path "README.md") {
    $readme = Get-Content "README.md" -Raw
    $readme = [regex]::Replace($readme, '# Suraksha.*?\n', "# Suraksha - Privacy & Security (v$rawDisplayVer)`n")
    $readme | Out-File -FilePath "README.md" -Encoding utf8
    Write-Host "[OK] Updated README.md" -ForegroundColor Green
}

Write-Host ""
Write-Host "=========================================" -ForegroundColor Cyan
Write-Host "  Build successfully updated to $displayVersion!" -ForegroundColor Green
Write-Host "=========================================" -ForegroundColor Cyan
